# Generated by Django 4.2 on 2023-04-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_vacancy_alter_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantsdata',
            name='cover_latter',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='applicantsdata',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
