# Generated by Django 4.2 on 2023-05-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_description_alter_job_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.TextField(max_length=200),
        ),
    ]
