# Generated by Django 4.2 on 2023-05-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='owner',
        ),
    ]
